export const raddiesData = [
  {
    year: 2026,
    edition: '6th',
    ordinal: 6,
    president: 'Jeff Loftin',
    honorary: ['Michael Sweet', 'Nick Bicât', 'Alonso Duralde'],
    awards: [
      { category: 'Raddest Animated TV Show Episode', winner: 'Joe Martinez' },
      { category: 'Raddest Music Episode', winner: 'Tim Babb & Mike Westfall' },
      { category: 'Raddest Episode Featuring Ozzy Osbourne and Gene Simmons', winner: 'Chad Young & Jeremy Phelps' },
      { category: 'Raddest Movie Score/Soundtrack Episode', winner: 'Kevin Williams' },
      { category: 'Raddest Bonus Episode', winner: 'Anthony Caruso & Jeremy Phelps' },
      { category: 'Raddest New Guest', winner: 'Laura Wonsik' },
      { category: 'Raddest Movie Episode', winner: 'Matt Spaulding & Jeremy Phelps' },
      { category: 'Raddest Halloween Episode', winner: 'Art Kilmer & Cecilia Davila' },
      { category: 'Raddest Theology Bros Episode', winner: 'Art Kilmer & Thom Crowe' },
      { category: 'Raddest Watchalong Episode', winner: 'CJ Bélanger & Anthony Caruso' },
      { category: 'Raddest Alternate Dimension Full of Siblings Episode', winner: 'Jeff Loftin & Joe Martinez' },
      { category: 'Raddest Catapult Dream Episode', winner: 'Matt Spaulding & Jeremy Phelps' },
      { category: 'Raddest Littles Episode', winner: 'Little #3 and Little #1' },
      { category: 'Raddest Live Action TV Show Episode (SCTV)', winner: 'Ken Kessler, Scott Leopold & Jeff Loftin' },
      { category: 'Raddest Disney Episode', winner: 'Tim Babb & Charlie Ague' },
      { category: 'Raddest Christmas TV Special Episode', winner: 'Ken Kessler' },
      { category: 'Raddest Christmas Villain Episode', winner: 'Nicholas Pepin (Pop Culture Roulette)' },
      { category: 'Raddest British "Santa Claus: The Movie" 40th Anniversary', winner: 'Adam Parker Sibun (Merry Britsmas)' },
      { category: 'Raddest Cowboy in Snowy Gulch', winner: 'Little #2' },
      { category: 'Raddest Comic Book Christmas Carol Episode', winner: 'Laramy Wells (Moving Panels)' },
      { category: "Raddest '80s Christmas Wrap Ups", winner: 'Joe Fulton' },
      { category: 'Raddest Christmas 2025 Episode', winner: 'Kristin Seering (Holidays After Dark)' },
      { category: 'Raddest Comic Brothers Re-Release', winner: 'CM Chuck & Anthony Caruso' },
      { category: 'Raddest Technical Raddies Host', winner: 'Sean Sotka' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Michael May & Chad Young' },
      { category: 'Raddest Original Script/Movie Novelization', winner: 'Pax Holley' },
      { category: 'Raddest Guaranteed Raddie-Winning Episode', winner: 'Mike Westfall & Tim Babb' },
      { category: 'Raddest Gag Me With A Spoon Impression', winner: 'Ken Kessler, Scott Leopold & Vinnie Brezinsky' },
      { category: 'Raddest Canadian Treasure Episode', winner: 'CJ Bélanger' },
      { category: 'Raddest Christmas Podcast Guest Host', winner: 'CJ Bélanger & Anthony Caruso' },
      { category: 'Raddest Non-Christmas Podcast Host', winner: 'William Bruce West & Chad Young' },
      { category: 'Raddest All-Star Episode', winner: 'Wrestling Bros' },
      { category: 'Raddest Hap-Hap-Happiest Moment', winner: 'Tim Babb & Charlie Ague' },
      { category: 'Raddest Half the Battle Guest', winner: 'CM Chuck' },
      { category: 'Raddest Guest Named Charlie', winner: 'Charlie Ague' },
      { category: 'Gerry D Award for Most Guest Appearances', winner: 'Anthony Caruso (43 appearances)', special: true },
    ],
  },
  {
    year: 2025,
    edition: '5th',
    ordinal: 5,
    president: null,
    honorary: [],
    awards: [
      { category: 'Raddest Animated TV Show Episode', winner: 'Shawn Robare' },
      { category: 'Raddest Music Episode', winner: 'Kevin Williams' },
      { category: 'Raddest Toy Episode', winner: 'Adam Pope' },
      { category: 'Raddest Game Show Episode', winner: 'Mike, Chad, and Tommy' },
      { category: 'Raddest Bonus Episode', winner: 'the Littles' },
      { category: 'Raddest New Guest', winner: 'Kevin Williams' },
      { category: 'Raddest Movie Episode', winner: 'Danny Davila' },
      { category: 'Raddest Halloween Episode', winner: 'Anthony Caruso and CM Chuck' },
      { category: 'Raddest Theology Bros Episode', winner: 'Art Kilmer and Thom Crowe' },
      { category: 'Raddest Christmas Special (Garbage Can) Episode', winner: 'Mike Patton and Rusty Spell' },
      { category: 'Raddest Mullet Episode', winner: 'Jeff and Jay' },
      { category: 'Raddest Life Day Episode', winner: 'Scott Newman and Jeremy Phelps' },
      { category: 'Raddest Wrestling Episode', winner: 'The Wrestling Bros' },
      { category: 'Raddest Live Action TV Show Episode', winner: 'Robbie Sherman and Tim Williams' },
      { category: 'Raddest Jim Henson Episode', winner: 'Mike Westfall and Tim Babb' },
      { category: 'Raddest Christmas TV Special Episode', winner: 'Jeff Loftin and Anthony Caruso' },
      { category: 'Raddest Podcast About Movie Novelizations', winner: 'Pax Holley' },
      { category: 'Raddest Drummer', winner: 'Duane Bailey' },
      { category: 'Raddest Non-Existent Podcast', winner: 'Manny Torres' },
      { category: 'Raddest 1987 CBS Christmas Specials Episode', winner: 'Matt and Jay' },
      { category: 'Raddest Hallmark Podcast', winner: 'John and Daniella' },
      { category: 'Raddest Steve Urkel Episode', winner: 'Matt Eurich' },
      { category: 'Raddest Sean Talking Raccoons Episode', winner: 'Sean Sotka' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Mike Westfall and Charlie Ague' },
      { category: 'Raddest Christmas-Adjacent Movie Episode', winner: 'Saturday Morning Mafia' },
      { category: 'Raddest Clue Episode', winner: 'Ken Kessler and Matt Spaulding' },
      { category: 'Raddest Comic Book Episode', winner: 'Jerzy Drozd' },
      { category: 'Raddest Gag Me with a Spoon Impression', winner: 'Mike Westfall and Tim Babb' },
      { category: 'Raddest Bonkers Theory', winner: 'Jeff Loftin & Jeremy Phelps' },
      { category: 'Raddest Christmas Podcast Guest Host', winner: 'Tim Babb and Mike Westfall' },
      { category: 'Raddest Non-Christmas Podcast Host', winner: 'Tim Williams and Nicholas Pepin' },
      { category: 'Raddest All-Star Episode', winner: 'Christmas Podcasters' },
      { category: 'Raddest Happiest Moment', winner: 'CJ Bélanger and Ashley Dunbar' },
      { category: 'Raddest Half the Battle Guess', winner: 'Tim Babb and Mike Westfall' },
      { category: 'Raddest Host of Advent Calendar House', winner: 'Mike Westfall' },
      { category: 'Raddest Most Edited Guest', winner: 'CJ Bélanger' },
      { category: 'Gerry D Award for Most Guest Appearances', winner: 'Anthony Caruso (37 appearances)', special: true },
    ],
  },
  {
    year: 2024,
    edition: '4th',
    ordinal: 4,
    president: 'Ashley Dunbar',
    honorary: [],
    awards: [
      { category: 'Raddest Animated TV Show Episode', winner: 'Matt Spaulding' },
      { category: 'Raddest Music Episode', winner: 'Ken Kessler' },
      { category: 'Raddest Disney Episode', winner: 'Mike Westfall & Charlie Ague' },
      { category: 'Raddest Bonus Episode', winner: 'Vinnie Brezinsky' },
      { category: 'Raddest New Guest', winner: 'Chad and Seth the Christmas Cousins' },
      { category: 'Raddest Movie Episode', winner: 'Bob Baker' },
      { category: 'Raddest Halloween Episode', winner: 'Anthony Caruso & CM Chuck' },
      { category: 'Raddest Ensemble Episode', winner: 'CJ, Ashley & Anthony' },
      { category: 'Raddest Thanksgiving Episode', winner: 'Anthony, Charlyn & Manny' },
      { category: 'Raddest Live Action TV Show Episode', winner: 'Scott Newman' },
      { category: 'Raddest Christmas TV Special Episode', winner: 'Thom Crowe' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Mike Westfall & Chad Young' },
      { category: 'Raddest Mafia of Saturday Morning', winner: 'Saturday Morning Mafia' },
      { category: 'Raddest Aficionado of Christmas', winner: 'Joe Fulton' },
      { category: 'Raddest Santa is a Mutant Episode', winner: 'Laramy Wells (Moving Panels)' },
      { category: "Raddest Flashback for '80s Flicks", winner: "Tim Williams ('80s Flick Flashback)" },
      { category: 'Raddest Jim Carrey Vampire Movie Episode', winner: 'Joe Martinez (Now Watch This)' },
      { category: 'Raddest Festivus Episode', winner: 'Matt Eurich (TGI Podcast)' },
      { category: 'Raddest Sean Talking Trolls Episode', winner: 'Sean Sotka' },
      { category: 'Raddest Christmas Adjacent Movie Episode', winner: 'CJ, Ashley & Anthony' },
      { category: 'Raddest Comic Book Episode', winner: 'AA & CM Chuck' },
      { category: 'Raddest Food Episode', winner: 'Anthony Caruso & CM Chuck' },
      { category: 'Raddest Gag Me with a Spoon Impression', winner: 'Tim Babb' },
      { category: 'Raddest Christmas Podcast Guest Host', winner: 'Tim Babb' },
      { category: 'Raddest Non-Christmas Podcast Host', winner: 'AA & CM Chuck' },
      { category: 'Raddest All-Star Episode', winner: 'Thom Crowe' },
      { category: 'Raddest Hap-Hap-Happiest Moment', winner: 'Ed Daly' },
      { category: 'Raddest Half the Battle Guest', winner: 'Mike Westfall & Chad Young' },
      { category: 'Raddest Guest Named Thom Crowe', winner: 'Thom Crowe' },
      { category: 'Gerry D Award for Most Guest Appearances', winner: 'Anthony Caruso (32 appearances)', special: true },
    ],
  },
  {
    year: 2023,
    edition: '3rd',
    ordinal: 3,
    president: null,
    honorary: ['Rachel Murray', 'Katie Leigh', 'Captain Sensible', 'Patric J Miller', 'Darcy Marta', 'Michael B Moynahan'],
    awards: [
      { category: 'Raddest Guest Duo', winner: 'Saturday Morning Mafia' },
      { category: 'Raddest Music Episode', winner: 'Duane, Ken, Todd, Scott, Scott & Vinnie' },
      { category: 'Raddest Toy Episode', winner: 'Mike Westfall' },
      { category: 'Raddest Bonus Episode', winner: 'Rad Santa' },
      { category: 'Raddest New Guest', winner: 'Ken Kessler' },
      { category: 'Raddest Score from a Christmas Movie/Special', winner: 'John Williams' },
      { category: 'Raddest Movie Episode', winner: 'Anthony Caruso and CJ Bélanger' },
      { category: 'Raddest Halloween Episode', winner: 'Little #1' },
      { category: 'Raddest Ensemble Episode', winner: 'Wrestling Bros' },
      { category: 'Raddest Thanksgiving Episode', winner: 'Anthony Caruso and CJ Bélanger' },
      { category: 'Raddest TV Show Episode', winner: 'Sean Sotka and Ken Kessler' },
      { category: 'Raddest Christmas TV Special Episode', winner: 'Anthony Caruso' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Saturday Morning Mafia' },
      { category: 'Raddest Deep Dive', winner: 'Robert Nicholas' },
      { category: 'Raddest Graphic Design', winner: 'Charlie Ague' },
      { category: 'Raddest Home Arcade', winner: 'Jeff Loftin' },
      { category: 'Raddest Podcast Adventure', winner: 'Adam Parker Sibun' },
      { category: 'Raddest Guest (Scheduling Conflict)', winner: 'Kristin Seering' },
      { category: 'Raddest Imaginary Listener Interaction', winner: 'Tim Babb' },
      { category: 'Raddest Shortest Podcast Host', winner: 'Ashley Dunbar' },
      { category: 'Raddest "I\'ll Be Back" Moment', winner: 'Thom Crowe' },
      { category: 'Raddest Impression', winner: 'Mike Westfall and Todd Killian' },
      { category: 'Raddest Book Episode', winner: 'Art Kilmer' },
      { category: 'Raddest Podcast Guest Host', winner: 'Mike Westfall and Todd Killian' },
      { category: 'Raddest Non-Christmas Podcast Host', winner: 'Danielle Clarke' },
      { category: 'Raddest Video Game Episode', winner: 'Mike Westfall & Todd Killian' },
      { category: 'Raddest All-Star Episode', winner: 'Wrestling Bros' },
      { category: 'Raddest Moment', winner: 'Ed Daly' },
      { category: 'Raddest Guess', winner: 'Anthony Caruso and Danny Davila' },
      { category: 'Raddest Song Adaptation', winner: 'The Davila 5' },
      { category: 'Raddest Texan', winner: 'AA and CM Chuck' },
      { category: 'Raddest Beard', winner: 'Ron Hogan and Jason Rhodes' },
      { category: 'Gerry D Award for Most Guest Appearances', winner: 'Anthony Caruso (23 appearances)', special: true },
    ],
  },
  {
    year: 2022,
    edition: '2nd',
    ordinal: 2,
    president: 'Kristin Black',
    honorary: [],
    awards: [
      { category: 'Raddest Guest Duo', winner: 'Saturday Morning Mafia' },
      { category: 'Raddest Music Episode', winner: 'Carrie Brown' },
      { category: 'Raddest Toy Episode', winner: 'AA and CM Chuck' },
      { category: 'Raddest Bonus Episode', winner: 'Josh Allen' },
      { category: 'Raddest New Guest', winner: 'Marty Achatz' },
      { category: 'Raddest Movie Episode', winner: 'Danny Davila' },
      { category: 'Raddest Halloween Episode', winner: 'The Volcanics' },
      { category: 'Raddest Ensemble Episode', winner: 'Wrestling Bros' },
      { category: 'Raddest Action Flick Episode', winner: 'Todd Killian' },
      { category: 'Raddest TV Show Episode', winner: 'Matt Eurich' },
      { category: 'Raddest Christmas TV Special Episode', winner: 'Julia Colburn and Anthony Caruso' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Lyle Perez' },
      { category: 'Raddest Guest New Yorker', winner: 'Anthony Caruso' },
      { category: 'Raddest Website Design', winner: 'Thom Crowe' },
      { category: 'Raddest Promo Theme Song', winner: 'Lucky and Joe from Now Watch This' },
      { category: 'Raddest Night Court Halloween Episode', winner: 'Chris and Kris' },
      { category: 'Raddest Unproduced Script', winner: 'Tim Babb' },
      { category: 'Raddest Guest (Scheduling Conflict)', winner: 'Cara Zelaya' },
      { category: 'Raddest Technical Raddie Award Show Host', winner: 'Sean Sotka' },
      { category: 'Raddest Merry Melee Host', winner: 'Todd Killian' },
      { category: 'Raddest Christmas Carol Adaptation', winner: 'Joe Martinez and Anthony Caruso' },
      { category: 'Raddest Super Secret Mail Away Episode', winner: 'Mike Westfall' },
      { category: 'Raddest Christmas Podcast Guest Host', winner: 'Thom Crowe and Anthony Caruso' },
      { category: 'Raddest Non-Christmas Podcast Host', winner: 'Danielle Clarke' },
      { category: 'Raddest All-Star Episode', winner: 'Thom, Anthony, Manny, Joe, CJ, and CM Chuck' },
      { category: 'Raddest Hap-Hap-Happiest Moment', winner: 'Anthony Caruso' },
      { category: 'Raddest Most Sentimental Christmas Memory', winner: 'The Davilas' },
      { category: 'Raddest Most Delicious Food', winner: 'Art Kilmer and CM Chuck' },
      { category: 'Raddest Beard', winner: 'Ron Hogan' },
      { category: 'Gerry D Award for Most Guest Appearances', winner: 'Anthony Caruso (15 appearances)', special: true },
    ],
  },
  {
    year: 2021,
    edition: '1st',
    ordinal: 1,
    president: 'Gerry D',
    honorary: [],
    awards: [
      { category: 'Raddest Guest Duo', winner: 'Saturday Morning Mafia', episode: "Knight Rider 'Silent Knight'" },
      { category: 'Raddest Music Episode', winner: 'Duane Bailey', episode: 'Last Christmas' },
      { category: 'Raddest Toy Episode', winner: 'Thom Crowe', episode: 'He-Man & She-Ra: A Christmas Special' },
      { category: 'Weirdest Christmas Moment', winner: 'Craig Kringle', episode: "Rudolph's Shiny New Year" },
      { category: 'Raddest Guest Named Todd', winner: 'Todd Killian', episode: "Newhart 'No Room at the Inn'" },
      { category: 'Raddest Movie Episode', winner: 'Danny Davila', episode: 'Home Alone' },
      { category: 'Raddest Guest New Yorker', winner: 'Chris and Kris', episode: 'Scrooged' },
      { category: 'Raddest TV Show/Special', winner: 'Rick Goldschmidt', episode: 'Rudolph the Red-Nosed Reindeer' },
      { category: 'Raddest Miscellaneous Episode', winner: 'Jason Rhodes and Chris Sisley', episode: 'Choose Your Own Adventure' },
      { category: 'Raddest Gag Me With a Spoon', winner: 'Todd Killian, as Destro', episode: "G.I. Joe 'Cobra C.L.A.W.S. Are Coming to Town'" },
      { category: 'Raddest Christmas Podcast Guest Host', winner: 'Tim Babb', episode: 'Superman' },
      { category: 'Raddest Guest from Christmas Travel Podcast', winner: 'Chris and Kris', episode: 'Ghostbusters' },
      { category: 'Raddest Hap-Hap-Happiest Moment', winner: 'Manny Torres', episode: 'Gremlins' },
      { category: 'Raddest Half the Battle Guess', winner: 'Glen Warren', episode: 'Christmas Food in Movies, pt. 1' },
      { category: 'Raddest Most Sentimental Christmas Memory', winner: 'The Davilas', episode: 'Davila Family Christmas yr1' },
      { category: 'Raddest Most Delicious Food', winner: 'Glen Warren (the pies)', episode: 'Christmas Food in Movies, pt. 1' },
      { category: 'Raddest Beard', winner: 'Jason Rhodes', episode: 'The Dukes of Hazzard' },
      { category: 'Raddest Kindest Guest', winner: 'Art Kilmer', episode: 'A Garfield Christmas Special' },
      { category: 'Raddest Nicest Guest', winner: 'Julia Colburn', episode: 'Cabbage Patch Kids' },
      { category: 'Gerry D Award for Most Appearances', winner: 'Thom Crowe (3 appearances)', special: true },
      { category: 'Clark Griswold Award', winner: 'Anthony Caruso', special: true },
    ],
  },
]
