export const CATEGORIES = [
  'All',
  'Main Dishes',
  'Sides & Salads',
  'Soups & Bisques',
  'Desserts',
  'Drinks & Cocktails',
  'Appetizers',
  'Breads & Sauces',
  'Questionable Classics',
]

export const recipes = [
  // ─── Questionable Classics ───────────────────────────────────────────────
  {
    id: 'jellied-beef-mold',
    title: 'Jellied Beef Mold',
    category: 'Questionable Classics',
    year: '1980s',
    servings: 8,
    image: '/recipes/jellied-beef-mold.jpg',
    tagline: '👀 Jellied. Beef. Mold. 👀',
    description:
      "With commentary notes by yours truly. Please — double all ingredients for a crowd. It says so right there at the end of the recipe.",
    ingredients: [
      '1½ pounds boneless beef chuck roast, cubed',
      '1 cup hot water',
      '1 envelope unflavored gelatin',
      '⅓ cup celery, chopped',
      '¼ cup onion, chopped',
      '¼ cup dill pickle, cubed',
      '10½ ounces beef consommé',
      '½ teaspoon salt',
      '⅛ teaspoon pepper',
      '12 olives with pimiento strips',
      '12 roasted red peppers',
      'Parsley, for garnish',
      'Stuffed olives, for garnish',
    ],
    steps: [
      "First you\'ll want to take perfectly good beef and simmer that up in water. Keep going until it\'s nice and tender. Save the broth — you\'re gonna need it later!",
      "After your meat is tender you\'re going to remove it and then put it through a food chopper. That\'s right… chop it using a coarse blade until it\'s meat mush.",
      "Once you are through pulverizing it, you should end it right here. Be done and walk away. Oh wait my bad, I mean you should end up with 2 cups of above mentioned meat mush.",
      "Cool the broth you reserved from the boiled meat and then soften gelatin in 2 tbsp. broth.",
      "Cook celery and onion in broth until tender, but still slightly firm, about 10 minutes. Drain, save broth. Mix celery, onion and pickle with meat. I love pickles, don\'t you? Doesn\'t that sound tasty so far???",
      "Next add enough broth to consommé to make 2 cups; heat. Add softened gelatin, stir to dissolve. Pour a thin layer of gelatin into 1½ quart loaf pan or 6 cup mold; chill.",
      "To remainder of gelatin mixture, add salt, pepper and beef mixture.",
      "Arrange olive slices and pimiento strips in design over gelatin in pan. You\'re going to want to make it look pretty so plan your design out ahead of time if needed. Presentation is everything!",
      "Carefully spoon in beef mixture, chill.",
      "To serve, unmold on platter, garnish with parsley and stuffed olives if desired.",
      "Double for a crowd. Yes — double for a crowd. Unmold. Serve. Enjoy.",
    ],
    notes: "8 Servings. Double for a crowd.",
    contributor: {
      name: 'Thom Crowe',
      url: 'https://instagram.com/thomcrowe',
    },
  },

  // ─── Appetizers ──────────────────────────────────────────────────────────
  {
    id: 'veggie-appetizer-pizza',
    title: 'Veggie Appetizer Pizza',
    category: 'Appetizers',
    year: '1980s',
    servings: 36,
    tagline: 'Party food that belongs next to a Sony Walkman.',
    description:
      'A totally rad party staple from the crescent roll era — cream cheese, ranch dressing, and whatever veggies you have on hand. Perfect for any holiday bash.',
    ingredients: [
      '2 packages (8 oz each) refrigerated crescent roll dough',
      '12 oz cream cheese, softened',
      '1 cup sour cream',
      '1 envelope ranch salad dressing mix (about half of 1-oz package)',
      '¾ cup cucumber slices, cut in half',
      '2 cups fresh broccoli florets',
      '½ cup carrot slices',
      '¾ cup grape tomatoes, cut in half',
    ],
    steps: [
      'Preheat oven to 375°F.',
      'Unroll dough and press evenly onto bottom and up sides of an ungreased 15×10-inch baking sheet.',
      'Bake 10 to 15 minutes or until golden brown. Cool on wire rack at least 30 minutes.',
      'In a medium bowl, beat cream cheese with an electric mixer at medium speed until fluffy. Add sour cream and ranch dressing mix; beat until blended.',
      'Spread evenly over cooled crust. Arrange rows of cucumber, broccoli, carrots and tomatoes on top.',
      'Cut pizza into rectangles. Serve immediately, or cover and refrigerate up to 24 hours.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'texas-caviar',
    title: 'Texas Caviar',
    category: 'Appetizers',
    year: '1980s',
    servings: 18,
    tagline: "The dip that puts fancy caviar to shame.",
    description:
      'Black-eyed peas, black beans, roasted corn, and a punchy lime dressing — this Tex-Mex crowd-pleaser gets better as it sits overnight.',
    ingredients: [
      '1 tablespoon vegetable oil',
      '3 cups fresh corn (from 2 to 3 ears)',
      '2 cans (15 oz each) black-eyed peas, rinsed and drained',
      '1 can (15 oz) black beans, rinsed and drained',
      '1 cup halved grape tomatoes',
      '1 cup chopped bell pepper, any color',
      '½ cup finely chopped red onion',
      '1 jalapeño pepper, seeded and minced',
      '2 green onions, minced',
      '¼ cup chopped fresh cilantro',
      // dressing
      '2 tablespoons red wine vinegar',
      '1 tablespoon lime juice plus 1 teaspoon grated lime peel',
      '1 teaspoon salt',
      '1 teaspoon sugar',
      '½ teaspoon ground cumin',
      '½ teaspoon dried oregano',
      '½ teaspoon garlic powder',
      '¼ cup olive oil',
    ],
    steps: [
      'Heat vegetable oil in a large skillet over high heat. Add corn; cook and stir about 3 minutes or until lightly browned in spots. Place in a large bowl.',
      'Add beans, tomatoes, bell pepper, onion, jalapeño, green onions and cilantro.',
      'In a small bowl, whisk together vinegar, lime juice and peel, salt, sugar, cumin, oregano and garlic powder. Slowly whisk in olive oil until well blended.',
      'Pour dressing over salad; toss to coat. Cover and refrigerate at least 2 hours or overnight.',
      'Just before serving, stir in 1 tablespoon lime juice. Taste and adjust salt.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'creamy-cheesy-spinach-dip',
    title: 'Creamy Cheesy Spinach Dip',
    category: 'Appetizers',
    year: '1980s',
    servings: 8,
    tagline: 'Slow cooker magic for your holiday spread.',
    description:
      'Frozen spinach, pepper Jack cheese, and a slow cooker — this dip basically makes itself. Serve in cherry tomato shells for maximum \u201880s presentation.',
    ingredients: [
      '2 packages (10 oz each) frozen chopped spinach, thawed',
      '2 cups chopped onions',
      '1 teaspoon salt',
      '½ teaspoon garlic powder',
      '¼ teaspoon black pepper',
      '12 oz pepper Jack or Cheddar-flavored processed cheese product, cubed',
      'Assorted crackers and chips for serving',
      'Cherry tomatoes, tops removed (optional)',
    ],
    steps: [
      'Drain spinach and squeeze dry, reserving ¼ cup liquid.',
      'In slow cooker, combine spinach, reserved liquid, onions, salt, garlic powder and black pepper. Mix well.',
      'Cover and cook on HIGH for 1 hour.',
      'Stir in cheese; cook 30 minutes or until melted.',
      'Serve with crackers or chips, or fill cherry tomato shells.',
    ],
    notes: 'To thaw spinach quickly, remove wrapper from spinach containers and microwave on HIGH 3 to 4 minutes, or until just thawed.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'spinach-pepperoni-quiche',
    title: 'Spinach & Pepperoni Quiche',
    category: 'Appetizers',
    year: '1980s',
    servings: 12,
    tagline: 'Quiche was the ultimate \u201880s party food.',
    description:
      'Crescent roll crust, spinach, pepperoni, and Monterey Jack — this is the quiche that showed up at every \u201880s holiday party and was always the first thing gone.',
    ingredients: [
      '1 large red sweet pepper, coarsely chopped',
      '1 tablespoon cooking oil',
      '1 package (8 oz) refrigerated crescent rolls',
      '4 beaten eggs',
      '½ of a (10-oz) package frozen chopped spinach, thawed and well-drained',
      '1 cup shredded Monterey Jack cheese (4 oz)',
      '2 oz sliced pepperoni, cut into strips',
      '¼ cup milk',
      '2 tablespoons grated Parmesan cheese',
    ],
    steps: [
      'In a medium skillet cook sweet pepper in oil until crisp-tender; drain.',
      'Separate crescent rolls into triangles. Press rolls over bottom and sides of a 9-inch tart pan or quiche dish, pressing dough together well at seams.',
      'In a medium bowl combine pepper, eggs, spinach, Monterey Jack cheese, pepperoni, milk, and Parmesan cheese. Pour into crust-lined pan.',
      'Bake in a 350°F oven about 30 minutes or until set.',
      'Let stand about 10 minutes before cutting. Cut into wedges and serve warm.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'two-cheese-shrimp-tarts',
    title: 'Two-Cheese Shrimp Tarts',
    category: 'Appetizers',
    year: '1980s',
    servings: 12,
    tagline: 'Fancy enough for a Dynasty dinner party.',
    description:
      'Homemade pastry cups filled with a herbed cream cheese and ricotta filling studded with shrimp. These little tarts say "I tried" without saying "I spent all day in the kitchen."',
    ingredients: [
      // Crust
      '⅓ cup margarine or butter',
      '1 cup all-purpose flour',
      '1 egg yolk',
      '2 tablespoons milk',
      // Filling
      '1 (3-oz) package cream cheese with garlic and herbs',
      '¼ cup margarine or butter',
      '1 egg',
      '1 cup ricotta cheese',
      '2 tablespoons milk',
      '1 teaspoon finely snipped fresh dill or ⅛ teaspoon dried dillweed',
      '¼ teaspoon salt',
      '1 (6-oz) package frozen shrimp, peeled, cooked, and drained',
      'Chopped pimientos (optional)',
    ],
    steps: [
      'Combine margarine or butter, flour, egg yolk, and milk. Mix to form dough; divide into 12 pieces. Press each piece into lightly greased muffin cups, covering bottom and sides.',
      'Bake crust at 375°F for 15 minutes or until lightly browned. Cool.',
      'Beat cream cheese and butter until smooth. Add egg, ricotta, milk, dill, and salt; mix well. Stir in shrimp and pimientos.',
      'Spoon filling into crusts. Bake at 375°F for 20 to 25 minutes or until set. Cool slightly before serving.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'parmesan-puffs',
    title: 'Parmesan Puffs',
    category: 'Appetizers',
    year: '1980s',
    servings: 32,
    tagline: 'Light, airy, and totally irresistible.',
    description:
      'Golden choux pastry puffs showered in Parmesan cheese. Serve warm straight from the oven for maximum effect.',
    ingredients: [
      '1 recipe choux pastry dough',
      'Grated Parmesan cheese',
    ],
    steps: [
      'Place dough in a pastry bag fitted with a ⅝-inch-wide plain tip.',
      'On a greased baking sheet, pipe dough into 32 mounds, each about 1¾ inches in diameter. Sprinkle with grated Parmesan cheese.',
      'Bake in a 400°F oven for 20 to 25 minutes, or until puffy and golden. Serve warm.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Soups & Bisques ─────────────────────────────────────────────────────
  {
    id: 'crimson-bisque',
    title: 'Crimson Bisque',
    category: 'Soups & Bisques',
    year: '1980s',
    servings: 7,
    tagline: 'Red, festive, and ready in minutes.',
    description:
      'Tomato juice, chicken broth, and a splash of dry sherry make this quick bisque look like it took all day. Garnish with green onion brushes for extra \u201880s elegance.',
    ingredients: [
      '3 cups tomato juice',
      '1 (10¾-oz) can condensed chicken broth',
      '2 tablespoons brown sugar',
      '1 teaspoon Worcestershire sauce',
      '¼ teaspoon celery salt',
      '⅛ teaspoon onion powder',
      '¼ cup dry sherry',
      'Green onion brushes (optional garnish)',
      'Lemon peel strips (optional garnish)',
    ],
    steps: [
      'In a 3-quart saucepan combine all ingredients except sherry, onion brushes, and lemon peel; bring to boiling.',
      'Remove from heat; stir in sherry.',
      'Serve in individual soup bowls. Garnish with green onion brushes and lemon peel strips.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'broccoli-crab-bisque',
    title: 'Broccoli & Crab Bisque',
    category: 'Soups & Bisques',
    year: '1980s',
    servings: 7,
    tagline: 'Creamy, cheesy, and totally luxurious.',
    description:
      'Leeks, mushrooms, broccoli, and Jarlsberg cheese come together in a rich cream-based bisque with crabmeat. This is the soup that made guests feel like they were dining at a five-star restaurant.',
    ingredients: [
      '1 cup sliced leeks',
      '1 cup sliced fresh mushrooms',
      '1 cup fresh or frozen chopped broccoli, thawed and drained',
      '1 clove garlic, minced',
      '¼ cup butter or margarine',
      '¼ cup all-purpose flour',
      '¼ teaspoon dried thyme, crushed',
      '½ teaspoon salt',
      '¼ teaspoon black pepper',
      '1 small bay leaf',
      '3 cups chicken broth',
      '1 cup light cream',
      '¾ cup shredded Jarlsberg or Swiss cheese (3 oz)',
      '1 (6-oz) package frozen crabmeat, thawed and drained',
    ],
    steps: [
      'In a 3-quart saucepan, cook leeks, mushrooms, broccoli, and garlic in butter until crisp-tender.',
      'Blend in flour, thyme, salt, pepper, and bay leaf.',
      'Add chicken broth and cream all at once. Cook and stir until thickened and bubbly. Cook and stir 1 minute more.',
      'Add cheese; stir until melted. Add crabmeat; heat through.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'tex-mex-chili',
    title: 'Tex-Mex Style Chili',
    category: 'Soups & Bisques',
    year: '1980s',
    servings: 4,
    tagline: 'A little spice for your holiday table.',
    description:
      'Ground beef chili with diced tomatoes, green chiles, and a full packet of seasoning mix — this is exactly the kind of dish that showed up at every \u201880s potluck.',
    ingredients: [
      '1 pound ground beef',
      '1 cup chopped onion',
      '½ teaspoon black pepper',
      '¼ teaspoon salt',
      '2 cans (about 14 oz each) diced tomatoes with green chiles',
      '1 can (15 oz) chili beans in sauce',
      '1 cup water',
      '1 package (1¼ oz) chili seasoning mix',
      '1 cup (4 oz) shredded Cheddar cheese',
    ],
    steps: [
      'Brown beef in a large skillet over medium-high heat for 6 to 8 minutes, stirring to break up meat. Drain fat.',
      'Add onion, pepper and salt; cook and stir 5 minutes or until onion is tender.',
      'Stir in tomatoes, beans with sauce, water and seasoning mix.',
      'Simmer 25 minutes, stirring occasionally. Serve topped with shredded cheese.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Sides & Salads ──────────────────────────────────────────────────────
  {
    id: 'tex-mex-beans',
    title: 'Tex-Mex Beans',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 9,
    tagline: 'Slow cooker beans with serious flavor.',
    description:
      'Lentils, kidney beans, pinto beans, and bacon — all slow-cooked with tomatoes, garlic, and cumin. This is the kind of side dish that disappears before the main course.',
    ingredients: [
      '½ cup dried lentils, rinsed and sorted',
      '5 slices bacon',
      '1 onion, chopped',
      '1 can (15 oz) kidney beans, rinsed and drained',
      '1 can (15 oz) pinto beans, rinsed and drained',
      '1 can (14 oz) diced tomatoes',
      '3 tablespoons ketchup',
      '3 cloves garlic, minced',
      '1 teaspoon salt',
      '½ teaspoon ground cumin',
      '¼ teaspoon red pepper',
      '1 bay leaf',
    ],
    steps: [
      'Bring a large saucepan of water to a boil. Add lentils; cook 20 minutes or until tender. Drain and place in slow cooker.',
      'Cook bacon until crisp. Drain; crumble when cool. In the same skillet with bacon drippings, cook onion over medium heat 5 minutes or until softened. Add to slow cooker.',
      'Add bacon, beans, tomatoes, ketchup, garlic, salt, cumin, red pepper and bay leaf to slow cooker; mix well.',
      'Cover and cook on LOW for 5 to 6 hours or on HIGH for 3 to 4 hours. Remove and discard bay leaf before serving.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'savory-sausage-dressing',
    title: 'Savory Sausage Dressing',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 7,
    tagline: 'The stuffing upgrade your holidays need.',
    description:
      'Bulk pork sausage, mushrooms, rosemary, and herb stuffing mix — this dressing bakes up golden and savory and pairs perfectly with turkey or a holiday roast.',
    ingredients: [
      '1 package (12 oz) seasoned bulk pork sausage',
      '¼ cup Crisco oil',
      '½ cup chopped onion',
      '½ cup chopped celery',
      '1 clove garlic, minced',
      '1½ cups sliced fresh mushrooms',
      '½ teaspoon Worcestershire sauce',
      '¼ teaspoon dried rosemary leaves',
      '⅛ teaspoon pepper',
      '2 cups herb-seasoned stuffing mix',
      '1 egg, slightly beaten',
      '½ cup hot water',
      '1½ teaspoons instant chicken bouillon granules',
    ],
    steps: [
      'Preheat oven to 325°F.',
      'Cook sausage over medium-high heat until no longer pink. Drain. Transfer to a medium mixing bowl.',
      'Heat oil in a large skillet. Add onion, celery and garlic. Sauté over moderate heat until celery is tender-crisp.',
      'Add mushrooms, Worcestershire sauce, rosemary and pepper. Cook, stirring constantly, for 1 minute. Add mixture to sausage. Mix well.',
      'Stir in stuffing mix and egg. Dissolve bouillon in hot water; stir into stuffing mixture.',
      'Place in a 1½-quart casserole. Bake at 325°F for 30 to 35 minutes, or until heated through.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'lemon-parsley-stuffing',
    title: 'Lemon-Parsley Stuffing',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 14,
    tagline: 'Bright, herby, and perfectly seasoned.',
    description:
      'Lemon peel, fresh parsley, marjoram, and thyme give this classic stuffing a fresh, vibrant flavor. Use it to stuff your turkey or bake it as a stand-alone casserole.',
    ingredients: [
      '10 cups dry bread cubes (about 14 slices)',
      '1 cup finely chopped onion',
      '1 cup snipped parsley',
      '4 teaspoons finely shredded lemon peel',
      '2 teaspoons dried marjoram, crushed',
      '1 teaspoon dried thyme, crushed',
      '1 teaspoon salt',
      '½ teaspoon pepper',
      '2 cloves garlic, minced',
      '1 cup butter or margarine, melted',
      '2 slightly beaten eggs',
      '½ cup water',
      '¼ cup lemon juice',
    ],
    steps: [
      'Combine bread, onion, parsley, lemon peel, marjoram, thyme, salt, pepper, and garlic. Mix well.',
      'Combine melted butter, eggs, water, and lemon juice; toss with bread mixture.',
      'Use to stuff a 10- to 12-pound turkey, or spoon into a 2-quart casserole and bake uncovered at 325°F for 30 to 40 minutes.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'potatoes-supreme',
    title: 'Potatoes Supreme',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 16,
    tagline: 'Mashed potatoes elevated to supreme status.',
    description:
      'Fluffy mashed potatoes with cheese, egg, and a Parmesan breadcrumb topping. Can be made ahead and refrigerated — perfect for holiday entertaining.',
    ingredients: [
      '6 medium potatoes (2 lbs.), cooked and cubed',
      '2 eggs',
      '1 tablespoon grated Parmesan cheese',
      '1 tablespoon fine dry bread crumbs',
      '2 teaspoons margarine or butter, melted',
      '1 tablespoon chopped onion',
      '¼ teaspoon salt',
      '⅛ teaspoon pepper',
      '1 cup milk',
      '1½ cups (6 oz) shredded cheese',
    ],
    steps: [
      'Spray baking dish with nonstick coating.',
      'Cook potatoes, onion, salt, and pepper in a small amount of water until tender; drain. Mash potatoes.',
      'Add egg, cheese, bread crumbs, and milk gradually, beating until fluffy. Spoon into baking dish; sprinkle with remaining cheese.',
      'Bake at 375°F for 20–25 minutes or until heated through.',
    ],
    notes: 'Make ahead: Cover and refrigerate up to 24 hours. Bake chilled mixture at 350°F for 45–60 minutes.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'sesame-holiday-vegetables',
    title: 'Sesame Holiday Vegetables',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 7,
    tagline: 'A colorful, toasty veggie side.',
    description:
      'Fennel, mixed frozen vegetables, and celery tossed with toasted sesame seeds, olive oil, and lemon juice. Festive, healthy, and ready in minutes.',
    ingredients: [
      '2 small fennel bulbs, cut into wedges',
      '1 (16-oz) package frozen mixed vegetables (broccoli, baby carrots, water chestnuts)',
      '2 cups sliced celery',
      '1 tablespoon sesame seed',
      '1 tablespoon olive oil',
      '1 tablespoon lemon juice',
      '½ teaspoon salt',
      '⅛ teaspoon pepper',
    ],
    steps: [
      'Cook fennel in a small amount of boiling water until tender; drain.',
      'Cook frozen vegetables as directed on package; drain.',
      'In skillet, cook sesame seeds in oil until lightly browned.',
      'Add vegetables, lemon juice, salt, and pepper. Toss gently and heat through.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'winter-greens-cranberry-vinaigrette',
    title: 'Winter Greens with Cranberry Vinaigrette',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 8,
    tagline: 'The salad that makes the whole table look good.',
    description:
      'Romaine, Belgian endive, cucumber, mushrooms, and avocado drizzled with a sweet-tart cranberry vinaigrette. Simple, elegant, and perfectly seasonal.',
    ingredients: [
      'Romaine or leaf lettuce',
      'Belgian endive',
      'Cucumber slices',
      'Mushrooms',
      'Red pepper strips',
      'Alfalfa sprouts',
      'Avocado slices',
      // Vinaigrette
      '½ cup cranberry juice cocktail',
      '2 tablespoons salad oil',
      '1 tablespoon red wine vinegar',
      '1 teaspoon sugar',
      '½ teaspoon salt',
    ],
    steps: [
      'Combine cranberry juice cocktail, salad oil, red wine vinegar, sugar, and salt; mix well.',
      'Arrange salad greens and vegetables on plates.',
      'Toss with dressing and serve immediately.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'pineapple-cranberry-relish',
    title: 'Pineapple Cranberry Relish',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 8,
    tagline: 'Better than anything that comes out of a can.',
    description:
      'Fresh cranberries, crushed pineapple, navel orange, and sugar blended into a chunky relish that mellows beautifully overnight. A must for the holiday table.',
    ingredients: [
      '1 can (8¼ oz) DOLE Crushed Pineapple in Syrup',
      '1 large thin-skinned navel orange, unpeeled',
      '1 package (12 oz) fresh cranberries, washed',
      '1 cup sugar',
    ],
    steps: [
      'Drain syrup from pineapple into a blender. Cut orange into 1-inch pieces; add to blender. Whir until coarse, stopping to stir as needed.',
      'Pour half of mixture into a bowl. Add half of cranberries to blender; whir until coarsely chopped. Repeat.',
      'Pour all into a bowl; add pineapple and sugar. Cover with plastic wrap and let stand at room temperature overnight.',
      'Store in tightly covered jars in refrigerator.',
    ],
    notes: 'Ripens and mellows beautifully when left on counter overnight.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'ambrosia',
    title: 'Ambrosia',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 8,
    tagline: 'The food of the gods, \u201880s style.',
    description:
      'Fresh orange sections layered with coconut and powdered sugar. A classic Southern holiday side that doubles as dessert.',
    ingredients: [
      '6 to 8 oranges',
      '⅓ cup sifted powdered sugar',
      '½ cup coconut',
      'Fresh cranberries (optional)',
      'Lime slices, halved (optional)',
    ],
    steps: [
      'Peel and section oranges over a bowl to catch juices.',
      'Add sugar to orange sections; toss to coat. Cover and refrigerate.',
      'Just before serving, layer orange sections and 1 tablespoon of the coconut in each goblet. Garnish with cranberries and lime slices.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'honey-lime-fruit-compote',
    title: 'Honey-Lime Fruit Compote',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 6,
    tagline: 'Fresh fruit dressed up for the holidays.',
    description:
      'Apple, pear, kiwi, and grapes tossed in a honey-lime dressing. Light, refreshing, and the perfect counterpoint to all that holiday richness.',
    ingredients: [
      '1 lime (juice)',
      '2 tablespoons sugar',
      '2 tablespoons honey',
      '1 apple, chopped',
      '1 pear, chopped',
      '1 kiwi, sliced',
      '½ cup grapes',
      'Fresh mint (optional)',
    ],
    steps: [
      'Combine lime juice, sugar, and honey.',
      'Add fruit; toss gently. Chill before serving.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'ham-rice-dressing',
    title: 'Ham and Rice Dressing',
    category: 'Sides & Salads',
    year: '1980s',
    servings: 9,
    tagline: 'A hearty dressing with chestnuts and ham.',
    description:
      'Roasted chestnuts, chopped ham, long-grain rice, and aromatics baked into a savory casserole dressing. A wonderful alternative to traditional bread stuffing.',
    ingredients: [
      '1 pound fresh chestnuts',
      '1 cup chopped onion',
      '½ cup chopped celery',
      '½ green pepper, chopped',
      '2 tablespoons cooking oil',
      '3 cups turkey or chicken broth',
      '2 cups chopped fully cooked ham',
      '1 cup long grain rice',
      '½ to 1 teaspoon pepper',
      '½ teaspoon salt',
      '⅛ teaspoon ground red pepper',
      '2 beaten eggs',
    ],
    steps: [
      'Cut an X in the flat side of each chestnut; bake at 350°F for 20 to 25 minutes; cool, peel, and coarsely chop.',
      'Cook onion, celery, and green pepper in hot oil until tender. Add chestnuts, 3 cups broth, ham, uncooked rice, and seasonings. Cover; simmer 30 minutes.',
      'Remove from heat. Combine remaining broth and eggs; stir into mixture. Pour into buttered 1½- to 2-quart casserole; bake at 350°F for 45 to 60 minutes.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Main Dishes ─────────────────────────────────────────────────────────
  {
    id: 'turkey-apple-citrus-stuffing',
    title: 'Turkey with Apple Citrus Stuffing',
    category: 'Main Dishes',
    year: '1980s',
    servings: 11,
    tagline: 'The centerpiece your holiday table deserves.',
    description:
      'A whole Butterball turkey stuffed with a fragrant apple, parsley, and orange stuffing. The kind of roast that makes the whole house smell like Christmas.',
    ingredients: [
      '1 (12- to 14-lb) Butterball turkey, thawed if frozen',
      '1 cup chopped celery',
      '½ cup chopped onion',
      '6 tablespoons margarine or butter',
      '2 teaspoons poultry seasoning',
      '8 cups slightly dried bread cubes (10–12 slices, cubed and dried overnight)',
      '2 cups chopped red apple',
      '¼ cup chopped fresh parsley',
      '1½ teaspoons shredded orange peel',
      'Juice from 1 orange plus water to make ¾ cup',
    ],
    steps: [
      'Cook and stir celery and onion in margarine in a medium saucepan over medium heat until crisp-tender. Stir in poultry seasoning.',
      'In a large bowl, combine bread cubes, apple, parsley and orange peel. Add celery mixture and orange juice mixture; toss to mix.',
      'Preheat oven to 325°F. Prepare turkey for roasting; stuff neck and body cavities lightly.',
      'Roast immediately according to package directions.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'orange-glazed-turkey',
    title: 'Orange-Glazed Turkey',
    category: 'Main Dishes',
    year: '1980s',
    servings: 14,
    tagline: 'Basted to golden perfection with orange butter.',
    description:
      'A boneless turkey roast basted with fresh orange juice and butter, finished with an orange liqueur pan sauce. Pure \u201880s elegance.',
    ingredients: [
      '1 (4- to 6-lb) frozen boneless turkey roast',
      '¾ cup butter or margarine, melted',
      '6 small oranges',
      '¼ cup water',
      '2 tablespoons all-purpose flour',
      '¼ teaspoon ground nutmeg',
      '2 tablespoons orange liqueur',
      'Sugar-coated cranberries and kumquats (optional garnish)',
      'Curly endive and cranberry-orange relish (optional)',
    ],
    steps: [
      'Thaw turkey. Place on rack in a shallow roasting pan. Brush with some of the butter.',
      'Roast according to package directions. Finely shred the peel of 1 orange to obtain 1 tablespoon peel; set aside. Juice all oranges (should have about 2 cups juice).',
      'Stir together remaining melted butter and orange juice. Baste turkey with orange juice mixture frequently during the last 30 minutes of roasting.',
      'Remove turkey to meat platter; cover to keep warm. Combine pan juices and remaining orange juice mixture; add water if necessary to make 2 cups.',
      'In a saucepan combine water and flour; add orange juice mixture, orange peel, and nutmeg. Cook and stir till thickened and bubbly; cook 2 minutes more. Stir in orange liqueur.',
      'Spoon some sauce over turkey; pass remaining sauce. Garnish as desired.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'peppered-chutney-roast',
    title: 'Peppered Chutney Roast',
    category: 'Main Dishes',
    year: '1980s',
    servings: 14,
    tagline: 'Beef tenderloin worthy of a Dynasty dinner.',
    description:
      'Beef tenderloin marinated in a tangy pineapple-Worcestershire mixture, coated in cracked pepper, and finished with a spoonful of chutney. The most dramatic main course you can serve.',
    ingredients: [
      '¼ cup unsweetened pineapple juice',
      '¼ cup steak sauce',
      '⅓ cup Worcestershire sauce',
      '⅓ cup port wine',
      '¼ cup lemon juice',
      '2 teaspoons seasoned salt',
      '1 teaspoon pepper',
      '1 teaspoon lemon-pepper seasoning',
      '1 teaspoon dry mustard',
      '1 (3- to 4-lb) beef tenderloin',
      '2 teaspoons cracked pepper or 4 slices bacon',
      '⅓ cup chutney',
      'Hot cooked Brussels sprouts (optional)',
    ],
    steps: [
      'Stir together pineapple juice, steak sauce, Worcestershire sauce, port wine, lemon juice, seasoned salt, pepper, lemon-pepper seasoning, and dry mustard for marinade.',
      'Place meat in a large plastic bag in a baking dish. Pour marinade over meat; close bag. Refrigerate several hours or overnight, turning occasionally. Drain, reserving marinade.',
      'Rub beef tenderloin with cracked pepper. Place on rack in shallow roasting pan. Arrange bacon slices over tenderloin.',
      'Roast, uncovered, at 425°F for 30 to 45 minutes or until meat thermometer registers 135°F. Baste twice during roasting with reserved marinade.',
      'Spoon chutney evenly over tenderloin. Bake 5 to 10 minutes more or until thermometer registers 140°F.',
      'Remove tenderloin to serving platter. Let stand about 15 minutes before slicing. Serve with Brussels sprouts if desired.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'basil-stuffed-lamb-roast',
    title: 'Basil-Stuffed Lamb Roast',
    category: 'Main Dishes',
    year: '1980s',
    servings: 12,
    tagline: 'Butterflied leg of lamb at its finest.',
    description:
      'A butterflied leg of lamb spread with a savory spinach, basil, and crouton stuffing, then rolled and roasted until perfectly pink. A showstopper for the holiday table.',
    ingredients: [
      '¼ cup chopped onion',
      '¼ cup chopped celery',
      '2 cloves garlic, minced',
      '¼ cup olive or cooking oil',
      '2 beaten eggs',
      '1 (10-oz) package frozen chopped spinach, thawed',
      '¼ cup snipped parsley',
      '3 tablespoons fresh snipped basil (or 1 tablespoon dried basil, crushed)',
      '¼ teaspoon dried marjoram, crushed',
      '6 cups unseasoned croutons',
      '¼ cup grated Parmesan cheese',
      '1 (5- to 7-lb) leg of lamb, boned and butterflied',
      '1 teaspoon dried rosemary, crushed',
    ],
    steps: [
      'For stuffing, cook onion, celery, and garlic in oil until tender. In a large bowl combine eggs, spinach, parsley, basil, marjoram, and ¼ teaspoon pepper; add onion mixture. Stir in croutons and cheese. Drizzle with ⅓ cup water; toss lightly.',
      'Remove fell (pinkish-red, paper-thin layer) from surface of meat. Pound meat to an even thickness. Sprinkle with rosemary.',
      'Spread stuffing evenly over meat. Roll up; tie securely. Place roast, seam side down, on a rack in a shallow roasting pan. Insert meat thermometer in thickest portion.',
      'Roast, uncovered, in a 325°F oven for 1½ to 2 hours or until thermometer registers 150°F. Let stand 15 minutes before carving.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'pork-roast-pesto-stuffing',
    title: 'Pork Roast with Pesto Stuffing',
    category: 'Main Dishes',
    year: '1980s',
    servings: 12,
    tagline: 'Pesto in a pork roast? Totally tubular.',
    description:
      'A center-cut pork rib roast with pockets stuffed full of pesto, croutons, and sun-dried tomatoes. Pesto was the height of \u201880s sophistication — and this roast delivers.',
    ingredients: [
      '½ cup plain croutons, slightly crushed',
      '½ cup purchased pesto sauce',
      '¼ cup chopped sun-dried tomatoes or pimiento',
      '3- to 4-lb pork loin center rib roast, backbone loosened (6 ribs total)',
    ],
    steps: [
      'Combine croutons, pesto, and tomatoes for stuffing. Set aside.',
      'Place roast, rib side down, on cutting surface. Cut a ¾-inch-deep pocket along each bone, making 6 pockets total. Spoon stuffing into pockets.',
      'Place roast in shallow roasting pan. Sprinkle with salt and pepper. Insert meat thermometer into thickest part, not touching bone.',
      'Bake at 325°F for 1½ to 2¼ hours or until thermometer registers 160°F. Cover loosely with foil after 1 hour to prevent overbrowning. Let stand before slicing.',
    ],
    notes: 'If using oil-packed sun-dried tomatoes, drain and chop. If using dry-packed, boil for 2 minutes before using.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'phyllo-roll-cranberry-sauce',
    title: 'Phyllo Roll with Cranberry Sauce',
    category: 'Main Dishes',
    year: '1980s',
    servings: 8,
    tagline: 'Buttery phyllo filled with ham, veggies, and cheese.',
    description:
      'Layers of buttered phyllo dough wrapped around a savory filling of ham, vegetables, and melted cheese. Serve with cranberry sauce for the ultimate holiday presentation.',
    ingredients: [
      '½ cup chopped celery',
      '½ cup chopped green pepper',
      '½ cup chopped onion',
      '1 cup diced ham',
      '½ cup mushrooms',
      '½ cup shredded cheese',
      '2 tablespoons flour',
      '½ teaspoon pepper',
      '¼ cup butter, melted',
      '1 tablespoon bread crumbs',
      '8 sheets phyllo dough',
      '1 beaten egg',
      'Cranberry sauce for serving',
    ],
    steps: [
      'Cook vegetables and ham until tender. Stir in cheese, flour, and seasoning.',
      'Layer phyllo sheets, brushing each with melted butter.',
      'Add filling and roll up tightly.',
      'Bake at 375°F until golden brown.',
      'Serve with cranberry sauce.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Breads & Sauces ─────────────────────────────────────────────────────
  {
    id: 'gooey-iced-cinnamon-rolls',
    title: 'Gooey Iced Cinnamon Rolls',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 12,
    tagline: 'Those famous mall cinnamon rolls — at home.',
    description:
      'Soft, pillowy yeast rolls filled with brown sugar and cinnamon, topped with a luscious cream cheese icing. These cream cheese-iced rolls were popularized in the \u201880s by a famous mall bakery chain. You know the one.',
    ingredients: [
      // Dough
      '1 package (¼ oz) active dry yeast',
      '1 cup warm milk (110°F)',
      '2 eggs, beaten',
      '½ cup granulated sugar',
      '⅓ cup butter, softened',
      '1 teaspoon salt',
      '4 cups all-purpose flour',
      // Filling
      '1 cup packed brown sugar',
      '3 tablespoons ground cinnamon',
      '6 tablespoons butter, softened',
      // Icing
      '1½ cups powdered sugar',
      '3 oz cream cheese, softened',
      '¼ cup (½ stick) butter, softened',
      '½ teaspoon vanilla',
      '⅛ teaspoon salt',
    ],
    steps: [
      'Dissolve yeast in warm milk in large bowl of electric mixer. Add eggs, sugar, butter and salt; beat at medium speed until well blended. Add flour; beat at low speed until dough comes together. Knead with dough hook until smooth and slightly sticky.',
      'Shape dough into a ball. Place in large greased bowl; turn to grease top. Cover and let rise in warm place until doubled, about 1 hour.',
      'Spray a 13×9-inch baking pan with nonstick cooking spray. Roll dough into an 18×14-inch rectangle. Spread with softened butter. Sprinkle evenly with brown sugar and cinnamon.',
      'Roll up dough tightly from long side; pinch seam to seal. Cut into 12 slices. Place slices cut-side up in pan. Cover and let rise about 30 minutes.',
      'Preheat oven to 350°F. Bake 20 to 25 minutes, or until golden brown.',
      'Beat together icing ingredients until smooth and creamy. Spread over warm rolls.',
    ],
    notes: 'These cream cheese-iced rolls were popularized in the \u201880s by a famous mall bakery chain. You know the one.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'cranberry-pumpkin-ring',
    title: 'Cranberry Pumpkin Ring',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 15,
    tagline: 'Festive, fragrant, and totally show-stopping.',
    description:
      'A pumpkin-spiced yeast ring filled with cranberry-orange filling and drizzled with a sweet orange glaze. The most dramatic bread you can put on the holiday table.',
    ingredients: [
      '3½ to 4 cups all-purpose flour',
      '1 package active dry yeast',
      '½ cup milk',
      '⅓ cup granulated sugar',
      '¼ cup butter or margarine',
      '1 teaspoon ground cinnamon',
      '½ teaspoon nutmeg',
      '¼ teaspoon cloves',
      '1 egg',
      '1 cup canned pumpkin',
      '1½ cups whole wheat flour',
      // Cranberry Filling
      '½ cup cranberries',
      '½ cup sugar',
      '1 teaspoon finely shredded orange peel',
      '½ teaspoon ground cinnamon',
      '2 tablespoons butter, softened',
      // Glaze
      '1 cup sifted powdered sugar',
      '4 teaspoons milk',
      '¼ teaspoon orange extract',
    ],
    steps: [
      'In a mixer bowl combine ½ cup flour and yeast. Heat milk, sugar, butter, and spices until warm (115° to 120°F). Add to flour; beat at low speed, then add egg and pumpkin. Beat 3 minutes on high. Stir in whole wheat flour and remaining all-purpose flour.',
      'Turn dough onto floured surface. Knead 6 to 8 minutes. Place in greased bowl; let rise until nearly double, about 1 hour.',
      'For filling, cook cranberries, sugar, orange peel, cinnamon, and 1 tablespoon water over medium heat until berries pop. Chill.',
      'Punch dough down; rest 10 minutes. Roll into 15×10-inch rectangle. Spread with softened butter and cranberry filling. Roll up jelly-roll style; seal seam. Form into a ring on a greased baking sheet.',
      'With kitchen shears, make cuts from outer edge to center at 1-inch intervals. Let rise 30 minutes.',
      'Bake at 375°F for 25 to 30 minutes, covering with foil last 10 minutes. Cool; drizzle with glaze.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'parmesan-walnut-bread',
    title: 'Parmesan-Walnut Bread',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 12,
    tagline: 'Quick bread with serious personality.',
    description:
      'A no-yeast quick bread packed with Parmesan and chopped walnuts. Wrap it overnight for best flavor — then slice and serve with the holiday spread.',
    ingredients: [
      '3 cups all-purpose flour',
      '¼ cup grated Parmesan cheese',
      '4 teaspoons baking powder',
      '½ teaspoon salt',
      '1 egg',
      '1⅓ cups milk',
      '¼ cup walnut or cooking oil',
      '1 cup chopped walnuts',
    ],
    steps: [
      'Combine flour, Parmesan cheese, baking powder, and salt in a large bowl.',
      'Stir together egg, milk, and oil; add to flour mixture, stirring just until combined. Fold in nuts.',
      'Turn into a greased 9×5×3-inch loaf pan. Bake at 350°F for about 1 hour or until a toothpick comes out clean.',
      'Cool in pan for 10 minutes; remove and cool completely. Wrap and store overnight before slicing.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'spiral-breadsticks',
    title: 'Spiral Breadsticks',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 16,
    tagline: 'Fun, twisty, and ready in no time.',
    description:
      'Refrigerated breadstick dough wrapped around skewers and baked until golden. Sprinkle with sesame seeds or your favorite seasoning. The easiest fancy-looking thing you will ever make.',
    ingredients: [
      '1 (8-oz) package refrigerated breadsticks',
      '8–12 skewers or chopsticks',
      '2 tablespoons sesame seed or seasoning',
    ],
    steps: [
      'Unwind dough into strips.',
      'Wrap each strip around skewers to form spirals. Place on greased baking sheet.',
      'Brush with milk; sprinkle with seasoning. Bake at 375°F until golden.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'bean-biscuits',
    title: 'Bean Biscuits',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 17,
    tagline: 'Old-fashioned biscuits, simple and perfect.',
    description:
      'Classic Southern-style biscuits made with lard, milk, and cold water. Thick, flaky, and golden — the kind of biscuit your grandma made.',
    ingredients: [
      '2 cups all-purpose flour',
      '1 teaspoon sugar',
      '½ teaspoon baking powder',
      '½ teaspoon salt',
      '¼ cup lard or shortening',
      '½ cup milk',
      '¼ cup cold water',
    ],
    steps: [
      'Stir together flour, sugar, baking powder, and salt. Cut in lard till mixture resembles coarse crumbs.',
      'Combine milk and water. Add liquid to flour mixture, 1 tablespoon at a time, to form dough.',
      'Turn onto lightly floured surface; knead gently. Roll to ¾-inch thickness; cut into biscuits.',
      'Place on ungreased baking sheet. Bake at 425°F for 18 to 20 minutes or until light brown.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'baked-cranberry-sauce',
    title: 'Baked Cranberry Sauce',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 8,
    tagline: 'Put down the canned stuff.',
    description:
      'Fresh cranberries baked with orange marmalade, pecans, coconut, and sugar into a rich, jammy sauce. Serve warm or chilled over fruit, ice cream, or alongside any holiday roast.',
    ingredients: [
      '1 pound cranberries (5 cups)',
      '1 (12-oz) jar (1 cup) orange marmalade',
      '1 cup chopped pecans',
      '1 cup coconut',
      '¾ cup sugar',
      '½ cup water',
    ],
    steps: [
      'Combine all ingredients. Spread in a 13×9×2-inch baking dish.',
      'Bake, uncovered, in a 350°F oven about 30 minutes.',
      'Transfer to small attractive jars. Store in refrigerator. Serve warm or chilled over fruit, ice cream, or as a meat accompaniment.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'tarragon-wine-mustard-sauce',
    title: 'Tarragon-Wine Mustard Sauce',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 6,
    tagline: 'The most \u201880s condiment you will ever make.',
    description:
      'Dijon mustard, dry white wine, olive oil, and fresh herbs whisked together in minutes. Pour into pretty little jars, tie a ribbon on top, and give it as a gift. Very Dynasty.',
    ingredients: [
      '½ cup Dijon-style mustard',
      '⅓ cup olive or cooking oil',
      '¼ cup white vinegar',
      '¼ cup dry white wine',
      '2 tablespoons dry mustard',
      '1 teaspoon dried basil, crushed',
      '1 teaspoon dried tarragon, crushed',
    ],
    steps: [
      'In a small bowl, stir together all ingredients.',
      'Transfer to small attractive jars. Cover and label.',
    ],
    notes: 'Serve with chilled meats, as a sauce on vegetables, or use to baste meats while cooking.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'gingered-holiday-chutney',
    title: 'Gingered Holiday Chutney',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 6,
    tagline: 'Sweet, tangy, and totally giftable.',
    description:
      'Fresh Anjou pears, sweet and hot peppers, raisins, and candied ginger simmered in brown sugar and vinegar into a gorgeous holiday chutney. Makes an excellent homemade gift.',
    ingredients: [
      '2 cups packed brown sugar',
      '⅓ cup vinegar',
      '¾ teaspoon salt',
      '¼ teaspoon ground cinnamon',
      '⅛ teaspoon ground red pepper',
      '1 lime',
      '1 lemon',
      '1 lb fresh Anjou pears, pared and coarsely chopped (about 3 cups)',
      '1 cup chopped green pepper',
      '1 cup chopped sweet red pepper',
      '1 cup chopped onion',
      '1 tablespoon chopped candied ginger',
      '1 cup light raisins',
    ],
    steps: [
      'In a saucepan combine brown sugar, vinegar, salt, cinnamon, and red pepper. Bring to boiling. Simmer, uncovered, 10 minutes.',
      'Finely shred peel from lime and lemon; squeeze juice. Add peel, juice, pears, peppers, onion, ginger, and raisins.',
      'Simmer uncovered, stirring occasionally, until mixture thickens. Cool; store in refrigerator.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'orange-streusel-muffins',
    title: 'Orange Streusel Muffins',
    category: 'Breads & Sauces',
    year: '1980s',
    servings: 12,
    tagline: 'The muffins that made breakfast special.',
    description:
      'Classic vanilla muffins topped with a brown sugar-cinnamon streusel. Simple, comforting, and perfect alongside a cup of coffee on Christmas morning.',
    ingredients: [
      '1¾ cups all-purpose flour',
      '¾ cup sugar',
      '2 teaspoons baking powder',
      '½ teaspoon salt',
      '1 egg',
      '¾ cup milk',
      '¼ cup cooking oil',
      '1 teaspoon vanilla',
      // Streusel Topping
      '2 tablespoons flour',
      '2 tablespoons brown sugar',
      '1 tablespoon margarine',
      'Cinnamon to taste',
    ],
    steps: [
      'Combine dry ingredients in a bowl.',
      'Mix egg, milk, oil, and vanilla together. Stir into dry ingredients just until combined.',
      'Fill muffin cups. Mix streusel ingredients and sprinkle over tops.',
      'Bake at 400°F for 20–25 minutes.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Desserts ────────────────────────────────────────────────────────────
  {
    id: 'classic-christmas-cake',
    title: 'Classic Christmas Cake',
    category: 'Desserts',
    year: '1980s',
    servings: 16,
    tagline: 'The Bundt cake of your holiday dreams.',
    description:
      'Cream cheese, butter, maraschino cherries, and pecans baked into a gorgeous Bundt cake with a powdered sugar glaze. Garnish with pecan halves and candied cherries for maximum \u201880s presentation.',
    ingredients: [
      '1 package (8 oz) cream cheese, softened',
      '1 cup butter or margarine, softened',
      '1½ cups granulated sugar',
      '1½ teaspoons vanilla',
      '1½ teaspoons ground cinnamon',
      '¼ teaspoon ground nutmeg',
      '4 eggs',
      '2¼ cups sifted cake flour',
      '1½ teaspoons baking powder',
      '1 jar (8 oz) maraschino cherries, drained and chopped',
      '1 cup finely chopped pecans',
      '1½ cups powdered sugar',
      '2 tablespoons milk',
      'Pecan halves and red and green candied cherries for garnish',
    ],
    steps: [
      'Preheat oven to 325°F. Beat cream cheese, butter, granulated sugar, vanilla and spices.',
      'Add eggs, one at a time, mixing well after each addition.',
      'Combine flour and baking powder. Gradually add 2 cups of the flour mixture to the butter mixture. To remaining flour mixture, add maraschino cherries and ½ cup of the chopped pecans; fold into batter.',
      'Grease a 10-inch Bundt or tube pan; sprinkle with remaining ½ cup pecans. Pour batter into prepared pan.',
      'Bake at 325°F for 1 hour and 15 minutes. Let cool in pan on wire rack 5 minutes. Remove from pan. Cool completely.',
      'Beat powdered sugar and milk until smooth. Spoon icing over cake. Garnish with pecan halves and candied cherries.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'chocolate-dipped-brandy-snaps',
    title: 'Chocolate Dipped Brandy Snaps',
    category: 'Desserts',
    year: '1980s',
    servings: 36,
    tagline: 'The most elegant cookie in the tin.',
    description:
      'Crispy, lacy tubes of spiced butter cookie dipped in Nestlé semi-sweet chocolate and rolled in nuts. Only six at a time — these need your full attention.',
    ingredients: [
      '½ cup butter',
      '½ cup sugar',
      '⅓ cup dark corn syrup',
      '½ teaspoon cinnamon',
      '¼ teaspoon ginger',
      '1 cup all-purpose flour',
      '2 teaspoons brandy',
      '1 (6-oz) package Nestlé Toll House Semi-Sweet Chocolate Morsels',
      '1 tablespoon vegetable shortening',
      '⅓ cup finely chopped nuts',
    ],
    steps: [
      'Preheat oven to 300°F.',
      'In a heavy gauge saucepan, combine butter, sugar, dark corn syrup, cinnamon, and ginger. Stir until melted and smooth. Remove from heat; stir in flour and brandy.',
      'Drop by rounded teaspoons onto ungreased cookie sheets, about 3 inches apart. Do NOT do more than six cookies at one time.',
      'Bake at 300°F for 10–12 minutes. Remove from oven; let stand a few seconds, then immediately roll around a wooden spoon handle to form a cylinder. Let cool.',
      'Melt chocolate morsels and shortening over hot (not boiling) water; stir until smooth. Dip each brandy snap halfway into melted chocolate.',
      'Sprinkle with nuts and place on waxed paper-lined cookie sheets. Chill until set. Store in refrigerator in an airtight container.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'mm-party-cookies',
    title: "M&M\'s Party Cookies",
    category: 'Desserts',
    year: '1980s',
    servings: 48,
    tagline: 'The cookie that defined \u201880s holiday baking.',
    description:
      'Classic drop cookies loaded with M&M candies in red and green for the holidays. The official cookie of every \u201880s Christmas party.',
    ingredients: [
      '1 cup shortening',
      '1 cup firmly packed brown sugar',
      '½ cup granulated sugar',
      '2 teaspoons vanilla',
      '2 eggs',
      '2¼ cups sifted all-purpose flour',
      '1 teaspoon salt (optional)',
      '1 teaspoon baking soda',
      '1½ cups M&M\'s plain candies (¾ lb.)',
    ],
    steps: [
      'Blend shortening and both sugars in a large bowl. Beat in vanilla and eggs.',
      'Sift remaining dry ingredients together; add to sugar-egg mixture, blending well.',
      'Stir in ½ cup of candies (reserve remaining candies for decorating).',
      'Drop from teaspoon onto ungreased cookie sheet; decorate tops with remaining candies.',
      'Bake in moderate oven (375°F) for 10 minutes, or until golden brown. Remove to wire racks; cool completely.',
    ],
    notes: 'After baking, some candies may be slightly cracked. This adds texture and interest!',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'eggnog-pie',
    title: 'Eggnog Pie',
    category: 'Desserts',
    year: '1980s',
    servings: 8,
    tagline: 'Everything you love about eggnog, in pie form.',
    description:
      'JELL-O instant pudding, dairy eggnog, a splash of rum, and Cool Whip in a graham cracker crust. This no-bake holiday pie is ready in minutes and gone in seconds.',
    ingredients: [
      '1 cup cold dairy or canned eggnog',
      '1 package (6-serving size) JELL-O Vanilla Flavor Instant Pudding and Pie Filling',
      '1 tablespoon rum or ¼ teaspoon rum extract',
      '¼ teaspoon nutmeg',
      '3½ cups (8 oz) Cool Whip Non-Dairy Whipped Topping, thawed',
      '1 prepared 8- to 9-inch graham cracker crumb crust, cooled',
    ],
    steps: [
      'Pour cold eggnog into a bowl. Add pie filling mix, rum and nutmeg. With an electric mixer at low speed, beat until blended, about 1 minute. Let stand 5 minutes.',
      'Fold in 2 cups of the whipped topping. Spoon into pie crust.',
      'Chill until firm, about 2 hours. Garnish with remaining whipped topping. Sprinkle with additional nutmeg, if desired.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'best-brownies',
    title: 'Best Brownies',
    category: 'Desserts',
    year: '1980s',
    servings: 16,
    tagline: 'The Hershey\'s brownie. The classic. The one.',
    description:
      'The famous Hershey\'s cocoa brownies with a creamy cocoa frosting. Dense, fudgy, and topped with a silky chocolate glaze. These are the brownies.',
    ingredients: [
      '½ cup butter or margarine, melted',
      '1 cup sugar',
      '1 teaspoon vanilla extract',
      '2 eggs',
      '½ cup all-purpose flour',
      '⅓ cup Hershey\'s Cocoa',
      '¼ teaspoon baking powder',
      '¼ teaspoon salt',
      '½ cup chopped nuts (optional)',
      // Frosting
      '3 tablespoons butter or margarine, softened',
      '3 tablespoons Hershey\'s Cocoa',
      '1 tablespoon light corn syrup or honey',
      '½ teaspoon vanilla extract',
      '1 cup confectioners\' sugar',
      '1 to 2 tablespoons milk',
    ],
    steps: [
      'Blend butter, sugar and vanilla in a large bowl. Add eggs; beat well.',
      'Combine flour, cocoa, baking powder and salt. Gradually blend into egg mixture. Stir in nuts if using.',
      'Spread batter in a greased 9-inch square pan. Bake at 350°F for 20 to 25 minutes, or until brownie begins to pull away from edges.',
      'For frosting, cream butter, cocoa, corn syrup and vanilla. Add confectioners\' sugar and milk; beat to spreading consistency. Frost cooled brownies and cut into squares.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'rich-cocoa-fudge',
    title: 'Rich Cocoa Fudge',
    category: 'Desserts',
    year: '1980s',
    servings: 36,
    tagline: 'Old-school stovetop fudge the right way.',
    description:
      'The classic Hershey\'s stovetop cocoa fudge — cook to soft-ball stage, cool without stirring, then beat until glossy. The process is meditative and the result is magnificent.',
    ingredients: [
      '3 cups sugar',
      '⅔ cup Hershey\'s Cocoa',
      '⅛ teaspoon salt',
      '1½ cups milk',
      '¼ cup butter or margarine',
      '1 teaspoon vanilla extract',
    ],
    steps: [
      'Butter an 8- or 9-inch square pan; set aside.',
      'In a heavy 4-quart saucepan, combine sugar, cocoa and salt; stir in milk.',
      'Cook over medium heat, stirring constantly, until mixture comes to a full rolling boil.',
      'Boil WITHOUT stirring to soft-ball stage (234°F). Remove from heat. Add butter and vanilla; do NOT stir.',
      'Cool at room temperature to 110°F (lukewarm). Beat until fudge thickens and loses some of its gloss.',
      'Quickly spread into prepared pan; let cool. Cut into 1- to 1½-inch squares.',
    ],
    notes: 'Nutty Variation: Beat cooked fudge as directed. Immediately stir in 1 cup broken almonds, pecans or walnuts. Marshmallow-Nut Variation: Increase cocoa to ¾ cup. Add 1 cup marshmallow creme with butter and vanilla; do not stir. Cool to 110°F. Beat 10 minutes; stir in 1 cup broken nuts.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'foolproof-dark-chocolate-fudge',
    title: 'Foolproof Dark Chocolate Fudge',
    category: 'Desserts',
    year: '1980s',
    servings: 32,
    tagline: 'Eagle Brand condensed milk makes it foolproof.',
    description:
      'Semi-sweet chocolate chips melted with Eagle Brand sweetened condensed milk — the easiest, most reliable fudge you will ever make. No thermometer required.',
    ingredients: [
      '3 (6-oz) packages semi-sweet chocolate chips',
      '1 (14-oz) can Eagle Brand Sweetened Condensed Milk (NOT evaporated milk)',
      'Dash salt',
      '½ to 1 cup chopped nuts',
      '1½ teaspoons vanilla extract',
    ],
    steps: [
      'In a heavy saucepan over low heat, melt chocolate chips with sweetened condensed milk and salt.',
      'Remove from heat; stir in nuts and vanilla.',
      'Spread evenly into a wax paper-lined 8- or 9-inch square pan. Chill 2 hours or until firm.',
      'Turn fudge onto cutting board; peel off paper and cut into squares. Store loosely covered at room temperature.',
    ],
    notes: 'Microwave method: In a 1-quart glass measure, combine chips with sweetened condensed milk. Microwave on HIGH for 3 minutes. Stir until smooth. Stir in remaining ingredients. Proceed as above.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'layered-mint-chocolate-candy',
    title: 'Layered Mint Chocolate Candy',
    category: 'Desserts',
    year: '1980s',
    servings: 24,
    tagline: 'Three layers of holiday perfection.',
    description:
      'Dark chocolate, creamy peppermint, dark chocolate again — this layered candy uses Eagle Brand condensed milk and semi-sweet chips. Cut into squares and watch them disappear.',
    ingredients: [
      '1 (12-oz) package semi-sweet chocolate chips',
      '1 (14-oz) can Eagle Brand Sweetened Condensed Milk (NOT evaporated milk)',
      '2 teaspoons vanilla extract',
      '6 oz white confectioners\' coating',
      '1 tablespoon peppermint extract',
      'Few drops green or red food coloring (optional)',
    ],
    steps: [
      'Melt chocolate chips with 1 cup sweetened condensed milk over low heat. Stir in vanilla. Spread half into a wax paper-lined 8- or 9-inch square pan; chill 10 minutes.',
      'Hold remaining chocolate at room temperature. Melt confectioners\' coating with remaining condensed milk over low heat. Stir in peppermint and food coloring. Spread over chilled chocolate layer; chill 10 minutes.',
      'Spread reserved chocolate over mint layer. Chill 2 hours.',
      'Turn onto cutting board; peel off paper and cut into squares. Store loosely covered at room temperature.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'peppermint-ice-cream-torte',
    title: 'Peppermint Ice Cream Torte',
    category: 'Desserts',
    year: '1980s',
    servings: 16,
    tagline: 'The frozen dessert that wows every crowd.',
    description:
      'Pound cake layered with peppermint ice cream and frosted with cream cheese buttercream. Freeze ahead, sprinkle with crushed candy canes before serving, and take all the credit.',
    ingredients: [
      '1 (10¾-oz) frozen loaf pound cake',
      '1 (½-gallon) carton brick-style peppermint, cherry, or chocolate ice cream',
      '2 (3-oz) packages cream cheese',
      '¼ cup margarine or butter',
      '1 teaspoon vanilla',
      '3 cups sifted powdered sugar',
      'Crushed red-striped peppermint candies or candy canes (optional)',
    ],
    steps: [
      'With a serrated knife, slice cake horizontally into fourths. Halve ice cream lengthwise; freeze one half. Cut remaining ice cream into two 1-inch-thick slices.',
      'Place 2 cake slices on a baking sheet. Top each with one ice cream slice. Top with remaining cake slices. Place in freezer.',
      'Beat cream cheese, margarine, and vanilla at medium speed about 30 seconds until fluffy. Gradually add powdered sugar, beating until smooth.',
      'Spread frosting over tops and sides of tortes. Freeze until firm.',
      'To serve, let stand covered at room temperature for 10 minutes. Sprinkle with crushed candies.',
    ],
    notes: 'Store in moisture- and vapor-proof containers in freezer up to 6 months.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'pistachio-almond-tartlets',
    title: 'Pistachio-Almond Tartlets',
    category: 'Desserts',
    year: '1980s',
    servings: 24,
    tagline: 'Tiny, elegant, and completely addictive.',
    description:
      'Cream cheese pastry cups filled with an almond-sour cream custard studded with pistachios. Top with a dab of currant jelly for maximum elegance. Can be made ahead and frozen.',
    ingredients: [
      // Crust
      '½ cup margarine or butter',
      '1 (3-oz) package cream cheese, softened',
      '1 cup all-purpose flour',
      // Filling
      '1 egg',
      '1 cup sugar',
      '½ cup sour cream',
      '½ cup almond paste, crumbled',
      '½ cup coarsely chopped pistachios or almonds',
      '¼ cup currant or red raspberry jelly (optional)',
    ],
    steps: [
      'Beat margarine and cream cheese until fluffy. Add flour; mix well. Chill about 1 hour. Divide into 24 equal portions; press each into an ungreased 1¾-inch muffin cup.',
      'For filling, combine egg, sugar, and almond paste; beat until smooth. Stir in sour cream and chopped nuts.',
      'Spoon filling into each crust. Bake in a 325°F oven for 25 to 30 minutes or until golden. Cool completely.',
      'To serve, thaw if frozen. Spoon a little jelly over each tartlet if desired.',
    ],
    notes: 'Store tightly covered at room temperature up to 1 week, or freeze up to 2 months.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'chocolate-macadamia-bars',
    title: 'Chocolate Macadamia Bars',
    category: 'Desserts',
    year: '1980s',
    servings: 16,
    tagline: 'Dark chocolate, white chocolate, macadamia nuts.',
    description:
      'A dense, fudgy chocolate bar loaded with macadamia nuts and white baking bar chunks, dusted with powdered sugar. The most indulgent thing in the cookie tin.',
    ingredients: [
      '1 (6-oz) package semisweet chocolate pieces',
      '2 oz unsweetened chocolate',
      '2 tablespoons margarine or butter',
      '2 eggs',
      '1 teaspoon vanilla',
      '¾ cup all-purpose flour',
      '½ teaspoon baking powder',
      'Dash salt',
      '1 cup chopped macadamia nuts or pecans',
      '2 oz white baking bar with cocoa butter, chopped',
      'Powdered sugar',
    ],
    steps: [
      'Melt chocolate pieces, unsweetened chocolate, and margarine over low heat, stirring constantly. Remove from heat; cool about 10 minutes.',
      'Stir in sugar. Add eggs one at a time, beating well. Stir in flour, baking powder, and salt. Fold in nuts and white baking bar.',
      'Spread batter in a greased 8×8×2-inch baking pan. Bake at 350°F for 30 minutes. Cool completely.',
      'Sift powdered sugar over top. Cut into bars.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'linzer-apple-torte',
    title: 'Linzer Apple Torte',
    category: 'Desserts',
    year: '1980s',
    servings: 10,
    tagline: 'European elegance meets \u201880s holiday entertaining.',
    description:
      'A hazelnut pastry crust filled with sliced apples and raspberry preserves. The kind of tart that makes everyone think you went to culinary school.',
    ingredients: [
      '1¾ cups flour',
      '1 cup ground hazelnuts or almonds',
      '¾ cup sugar',
      '½ teaspoon cinnamon',
      '½ cup butter',
      '1 egg',
      'Apples, sliced',
      'Raspberry preserves',
    ],
    steps: [
      'Mix flour, nuts, sugar, and cinnamon. Add butter and egg to form dough.',
      'Press into tart pan. Add apples and raspberry preserves.',
      'Bake at 375°F for 35–40 minutes.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'steamed-cranberry-cherry-pudding',
    title: 'Steamed Cranberry-Cherry Pudding with Vanilla Cream',
    category: 'Desserts',
    year: '1980s',
    servings: 12,
    tagline: 'Old-world steamed pudding for the modern \u201880s host.',
    description:
      'A classic bread-and-custard steamed pudding with dried cherries, cranberries, and pecans, unmolded and served with fresh whipped vanilla cream. The most impressive dessert you will ever attempt.',
    ingredients: [
      '4 egg yolks',
      '2 cups milk',
      '½ cup sugar',
      '¼ teaspoon salt',
      '1 teaspoon vanilla',
      '1 teaspoon orange peel',
      '1 cup orange juice',
      '½ cup dried cherries',
      '½ cup dried cranberries',
      '21 slices firm white bread, cubed',
      '18 candied cherries',
      '½ cup pecans',
      // Vanilla Cream
      '1 cup whipping cream',
      '2 tablespoons sugar',
    ],
    steps: [
      'Prepare custard by heating egg yolks, milk, sugar, and salt until thickened. Add vanilla and orange peel.',
      'Soak dried cherries and cranberries in orange juice. Cube bread and combine with custard and fruit.',
      'Layer mixture in greased mold with candied cherries and pecans.',
      'Steam in covered mold over simmering water for 1½–2 hours. Cool slightly; unmold.',
      'Whip cream with sugar. Serve pudding with whipped vanilla cream.',
    ],
    contributor: { name: 'Gerry D' },
  },

  // ─── Drinks & Cocktails ──────────────────────────────────────────────────
  {
    id: 'apple-spice-egg-nog',
    title: 'Apple Spice Egg Nog',
    category: 'Drinks & Cocktails',
    year: '1980s',
    servings: 14,
    tagline: 'The holiday punch bowl hero.',
    description:
      'Borden Egg Nog mixed with apple cider and cinnamon. Three ingredients. Done. The easiest holiday drink that tastes like you planned everything.',
    ingredients: [
      '3 (32-oz) cans Borden Egg Nog, chilled',
      '3 cups apple cider, chilled',
      '½ teaspoon ground cinnamon',
    ],
    steps: [
      'In a large bowl, combine ingredients; mix well. Chill. Garnish as desired. Refrigerate leftovers.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'cranberry-cheesecake-shake',
    title: 'Cranberry Cheesecake Shake',
    category: 'Drinks & Cocktails',
    year: '1980s',
    servings: 5,
    tagline: 'The shake that tastes like Christmas.',
    description:
      'Cream cheese, vanilla ice cream, jellied cranberry sauce, and fresh cranberries blended into a rich, festive shake. Weird on paper. Amazing in a glass.',
    ingredients: [
      '1 egg',
      '1 (3-oz) package cream cheese, softened',
      '½ cup milk',
      '2 cups vanilla ice cream',
      '1 (8-oz) can jellied cranberry sauce',
      '1 cup cranberries',
    ],
    steps: [
      'Place egg in blender container. Cover and blend 15 to 30 seconds.',
      'Add cream cheese and milk. Cover and blend till well combined.',
      'Add ice cream, cranberry sauce, and cranberries. Blend till well combined. Serve immediately, or cover and chill.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'hot-buttered-cranberry-toddy',
    title: 'Hot Buttered Cranberry Toddy',
    category: 'Drinks & Cocktails',
    year: '1980s',
    servings: 10,
    tagline: 'Warm up from the inside out.',
    description:
      'Cranberry juice cocktail simmered with lemon peel and cloves, finished with a pat of butter. Serve hot at any holiday gathering and watch everyone hold their mugs like they\'re in a Hallmark movie.',
    ingredients: [
      '5 cups cranberry juice cocktail',
      '3 cups water',
      '1-inch-long strips lemon peel',
      '¼ cup lemon juice',
      '3 whole cloves',
      '2 tablespoons butter or orange juice',
    ],
    steps: [
      'In a saucepan or Dutch oven combine cranberry juice cocktail, water, lemon peel, and cloves. Bring to boiling; reduce heat and simmer 10 minutes.',
      'Remove spices. Add butter and stir until melted. Serve hot.',
    ],
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'spiced-eggnog-cocoa',
    title: 'Spiced Eggnog Cocoa',
    category: 'Drinks & Cocktails',
    year: '1980s',
    servings: 17,
    tagline: 'Hot cocoa and eggnog had a delicious baby.',
    description:
      'Instant cocoa mix spiced with mace, allspice, and nutmeg, stirred into eggnog and water. Top with pressurized whipped cream and a drizzle of crème de menthe for the full holiday effect.',
    ingredients: [
      '1 (16-oz) can instant cocoa mix',
      '½ teaspoon ground mace',
      '¼ teaspoon ground allspice',
      '¼ teaspoon ground nutmeg',
      '8 cups water',
      '1 quart dairy eggnog',
      'Pressurized whipped dessert topping',
      'Green crème de menthe or grenadine syrup',
    ],
    steps: [
      'In a 1-quart airtight container, combine cocoa mix, mace, allspice, and nutmeg. Cover; store at room temperature.',
      'To serve: In a 4½-quart Dutch oven, bring water to boiling. Stir in cocoa mixture and eggnog. Heat through.',
      'Top each serving with whipped topping and drizzle with crème de menthe or grenadine.',
    ],
    notes: 'For individual servings: Bring ½ cup water to boiling. Stir in ¼ cup cocoa mixture and ¼ cup eggnog. Heat and serve.',
    contributor: { name: 'Gerry D' },
  },
  {
    id: 'white-grape-spritzers',
    title: 'White Grape Spritzers',
    category: 'Drinks & Cocktails',
    year: '1980s',
    servings: 4,
    tagline: 'The elegant non-alcoholic option.',
    description:
      'White grape juice and lemon-lime soda over fruit ice cubes. Simple, sparkling, and works for the whole family — or add champagne for the adults.',
    ingredients: [
      '2 cups white grape juice',
      '2 cups lemon-lime soda or champagne',
      'Fruit ice cubes (optional)',
    ],
    steps: [
      'Combine grape juice and soda.',
      'Serve chilled over ice or fruit cubes.',
    ],
    contributor: { name: 'Gerry D' },
  },
]
